In [1]:
import pandas as pd
import numpy as np

In [2]:
import chardet

with open("../artifacts/raw/EcoCrop_DB.csv", "rb") as f:
    result = chardet.detect(f.read(50000))
print(result)

{'encoding': 'Windows-1252', 'confidence': 0.7262460973370064, 'language': ''}

In [3]:
df = pd.read_csv("../artifacts/raw/EcoCrop_DB.csv", encoding="cp1252")

In [4]:
df.head()

,EcoPortCode,ScientificName,AUTH,FAMNAME,SYNO,COMNAME,LIFO,HABI,LISPA,PHYS,...,KTMPR,KTMP,PHOTO,CLIZ,ABITOL,ABISUS,INTRI,PROSY,GMIN,GMAX
0,289,Abelmoschus esculentus,(L.) Moench,Magnoliopsida:Dilleniidae:Malvales:Malvaceae,Hibiscus esculentus L.,"abelmoskus, america-neri, bakhua mun, bamia, b...",herb,erect,annual,single stem,...,NaN,NaN,short day (<12 hours),"tropical wet & dry (Aw), tropical wet (Ar), st...",NaN,NaN,NaN,NaN,50.0,180.0
1,290,Abelmoschus manihot,(L.) Medic.,Magnoliopsida:Dilleniidae:Malvales:Malvaceae,"Hibiscus manihot L. (1753), Abelmoschus maniho...","neka (Simbo), bele (Fiji), pele (Tonga, Tuvalu...",shrub,erect,"annual, perennial",NaN,...,NaN,NaN,long day (>14 hours),"tropical wet & dry (Aw), tropical wet (Ar)",NaN,NaN,NaN,NaN,365.0,365.0
2,291,Abelmoschus moschatus,Medic.,Magnoliopsida:Dilleniidae:Malvales:Malvaceae,Hibiscus abelmoschus L. (1753).,"abelmosk, musk mallow, mushkdan, muskdana, kas...","herb, sub-shrub",prostrate/procumbent/semi-erect,"annual, biennial, perennial","deciduous, multi stem",...,NaN,NaN,NaN,tropical wet & dry (Aw),NaN,NaN,can become a weed,NaN,0.0,0.0
3,295,Acacia auriculiformis,Cunn. ex Benth.,Magnoliopsida:Rosidae:Fabales:Leguminosae,Racosperma auriculiforme (A. Cunn. ex Benth.) ...,"Papuan wattle, auri, ear leaf acacia, tuhkehn ...",tree,erect,perennial,single stem,...,NaN,NaN,short day (<12 hours),"tropical wet & dry (Aw), tropical wet (Ar)","fire, drought",NaN,NaN,NaN,180.0,240.0
4,297,Acacia farnesiana,(L.) Willd.,Magnoliopsida:Rosidae:Fabales:Leguminosae,"Mimosa farnesiana L., Mimosa acicularis Poir.,...","Ellington curse, klu, cassie, espino blanco, a...",tree,erect,perennial,single stem,...,NaN,NaN,short day (<12 hours),"tropical wet & dry (Aw), steppe or semiarid (B...",NaN,NaN,can become a weed,NaN,60.0,240.0

In [5]:
df.describe()

,EcoPortCode,TOPMN,TOPMX,TMIN,TMAX,ROPMN,ROPMX,RMIN,RMAX,PHOPMN,...,PHMAX,LATOPMN,LATOPMX,LATMN,LATMX,ALTMX,KTMPR,KTMP,GMIN,GMAX
count,2568.000000,2071.000000,2071.000000,2068.000000,2068.000000,2067.000000,2067.000000,2065.000000,2065.000000,2080.000000,...,2080.000000,1224.000000,1009.000000,1862.00000,1854.000000,1775.000000,1157.000000,1157.000000,2566.000000,2566.000000
mean,33964.605530,18.859971,28.627233,9.745164,35.568665,968.502661,1662.769715,639.869249,2445.162228,5.663462,...,7.693317,23.133415,23.027056,35.60964,42.194633,1606.616901,-7.333621,-0.420916,127.160561,192.250195
std,89236.188565,5.702504,5.110292,4.517487,5.885098,645.486167,1016.465894,438.764350,1457.447348,0.663362,...,0.710181,27.848961,28.684771,78.41238,110.815239,900.764976,10.129150,2.306155,112.366932,137.433245
min,289.000000,5.000000,14.000000,2.000000,13.000000,125.000000,100.000000,50.000000,250.000000,4.000000,...,5.000000,1.000000,1.000000,2.00000,2.000000,20.000000,-50.000000,-20.000000,0.000000,0.000000
25%,2909.750000,15.000000,25.000000,6.000000,32.000000,500.000000,1000.000000,300.000000,1300.000000,5.000000,...,7.200000,12.000000,12.000000,20.00000,25.000000,1000.000000,-10.000000,-1.000000,0.000000,0.000000
50%,5930.500000,20.000000,28.000000,10.000000,35.000000,800.000000,1500.000000,500.000000,2000.000000,5.500000,...,7.500000,21.000000,21.000000,30.00000,34.000000,1500.000000,-5.000000,-1.000000,120.000000,210.000000
75%,10146.250000,22.000000,32.000000,13.000000,40.000000,1200.000000,2000.000000,800.000000,3500.000000,6.000000,...,8.200000,30.000000,30.000000,40.00000,45.000000,2100.000000,-2.000000,0.000000,180.000000,320.000000
max,400004.000000,160.000000,45.000000,25.000000,58.000000,9000.000000,12000.000000,3000.000000,9900.000000,8.000000,...,10.500000,700.000000,700.000000,2400.00000,2200.000000,6000.000000,14.000000,14.000000,365.000000,365.000000

In [6]:
df.isnull().sum()

EcoPortCode          0
ScientificName       0
AUTH               212
FAMNAME            182
SYNO              1811
COMNAME            913
LIFO               263
HABI               297
LISPA              283
PHYS               674
CAT                273
PLAT              1279
TOPMN              497
TOPMX              497
TMIN               500
TMAX               500
ROPMN              501
ROPMX              501
RMIN               503
RMAX               503
PHOPMN             488
PHOPMX             488
PHMIN              488
PHMAX              488
LATOPMN           1344
LATOPMX           1559
LATMN              706
LATMX              714
ALTMX              793
LIOPMN             441
LIOPMX             441
LIMN               442
LIMX               442
DEP                481
DEPR               485
TEXT               436
TEXTR              440
FER                481
FERR               584
TOX               2506
TOXR              2506
SAL                612
SALR               619
DRA                428
DRAR               432
KTMPR             1411
KTMP              1411
PHOTO              846
CLIZ               321
ABITOL            2028
ABISUS            2336
INTRI             2347
PROSY             2191
GMIN                 2
GMAX                 2
dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
useful_cols = [ 
    "ScientificName", 
    "COMNAME", 
    "PHMIN", "PHMAX",
    "RMIN", "RMAX",
    "TMIN", "TMAX"
]
df = df[useful_cols]

In [9]:
df.dropna(inplace=True)

In [10]:
df["COMNAME"] = df["COMNAME"].fillna("").apply(
    lambda x: [name.replace(" ", "_").strip() for name in x.split(",") if name.strip()]
)

In [11]:
def get_crop_ranges(crop_name: str):
    """
    Returns the pH, rainfall, and temperature ranges for a given crop name from EcoCrop DB.
    
    Parameters:
        crop_name (str): The crop to search for (exact match, case-insensitive)
        df (pd.DataFrame): The EcoCrop dataframe with 'COMNAME' as lists
    
    Returns:
        List[Dict]: Each dict contains ScientificName, COMNAME, PHMIN, PHMAX, RMIN, RMAX, TMIN, TMAX
    """
    crop_name = crop_name.lower().lstrip("_")  # normalize input
    
    def contains_only_crop(name_list):
        normalized = [name.lstrip("_").lower() for name in name_list]
        return crop_name in normalized
    
    mask = df["COMNAME"].apply(contains_only_crop)
    result_df = df[mask]
    
    # select relevant columns
    cols = ["ScientificName", "PHMIN", "PHMAX", "RMIN", "RMAX", "TMIN", "TMAX"]
    result_df = result_df[cols]
    
    # convert to list of dicts
    return result_df.to_dict(orient="records")

rice_ranges = get_crop_ranges("rice")
print(*rice_ranges)

{'ScientificName': 'Oryza sativa', 'PHMIN': 4.5, 'PHMAX': 9.0, 'RMIN': 1000.0, 'RMAX': 4000.0, 'TMIN': 10.0, 'TMAX': 36.0}

In [12]:
df.to_csv("../artifacts/processed/cleaned_EcoCrop_DB.csv", index=False)